image: node:alpine

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn run build

deploy:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - yarn run build-storybook
    - rm -rf public
    - mkdir public
    - mv storybook-static/* public/
  artifacts:
    paths:
      - public
