image: node:alpine

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn run build

deploy:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - yarn global add codecov
    - codecov

pages:
  stage: deploy
  script:
    - yarn run typedoc --out ./docs --includeDeclarations --excludeExternals src
    - rm -rf public
    - mkdir public
    - mv docs/* public/
  artifacts:
    paths:
      - public
