image: node:alpine

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn run build

lint:ts:
  stage: test
  script:
    - yarn lint:ts

lint:css:
  stage: test
  script:
    - yarn lint:css

test:
  stage: test
  script:
    - yarn test

deploy:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - yarn run typedoc --out ./docs --includeDeclarations --excludeExternals src
    - rm -rf public
    - mkdir public
    - mv docs/* public/
  artifacts:
    paths:
      - public
