image: node:jessie

cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
    - yarn install
    - yarn run build-storybook
    - mkdir -p dist/public
    - mv storybook-static/* public/
  artifacts:
    paths:
    - dist/public