version: 2
jobs:
  build:
    docker:
      - image: node:alpine

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run lint:ts
      - run: yarn run lint:css
      - run: yarn test
